GRH/Gestion de Recursos Humanos/Gestion de Recursos Humanos/Models/cargos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_de_Recursos_Humanos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cargos
    {
        public int Id { get; set; }
        public string cargo { get; set; }
    }
}

GRH/Gestion de Recursos Humanos/Gestion de Recursos Humanos/Controllers/cargosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Gestion_de_Recursos_Humanos.Models;

namespace Gestion_de_Recursos_Humanos.Controllers
{
    public class cargosController : Controller
    {
        private Model1Container db = new Model1Container();

        // GET: cargos
        public ActionResult Index()
        {
            return View(db.cargosSet.ToList());
        }

        // GET: cargos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cargos cargos = db.cargosSet.Find(id);
            if (cargos == null)
            {
                return HttpNotFound();
            }
            return View(cargos);
        }

        // GET: cargos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: cargos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,cargo")] cargos cargos)
        {
            if (ModelState.IsValid)
            {
                db.cargosSet.Add(cargos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cargos);
        }

        // GET: cargos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cargos cargos = db.cargosSet.Find(id);
            if (cargos == null)
            {
                return HttpNotFound();
            }
            return View(cargos);
        }

        // POST: cargos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,cargo")] cargos cargos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cargos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cargos);
        }

        // GET: cargos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cargos cargos = db.cargosSet.Find(id);
            if (cargos == null)
            {
                return HttpNotFound();
            }
            return View(cargos);
        }

        // POST: cargos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            cargos cargos = db.cargosSet.Find(id);
            db.cargosSet.Remove(cargos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
      

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GRH/Gestion de Recursos Humanos/Gestion de Recursos Humanos/Views/cargos/Create.cshtml
@model Gestion_de_Recursos_Humanos.Models.cargos

@{
    ViewBag.Title = "Create";
}

<h2 style="text-align:center">Crear Cargo</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal" style="margin-left:25%">
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.cargo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cargo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cargo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GRH/Gestion de Recursos Humanos/Gestion de Recursos Humanos/Views/cargos/Delete.cshtml
@model Gestion_de_Recursos_Humanos.Models.cargos

@{
    ViewBag.Title = "Delete";
}



<h2>Seguro que quieres eliminar este cargo?</h2>
<div>
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.cargo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cargo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Si, estoy seguro" class="btn btn-default" /> |
            @Html.ActionLink("Volver a lista", "Index")
        </div>
    }
</div>

GRH/Gestion de Recursos Humanos/Gestion de Recursos Humanos/Views/cargos/Details.cshtml
@model Gestion_de_Recursos_Humanos.Models.cargos

@{
    ViewBag.Title = "Detalles";
}

<h2>Detalles</h2>

<div>
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.cargo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cargo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Volver a la lista", "Index")
</p>

GRH/Gestion de Recursos Humanos/Gestion de Recursos Humanos/Views/cargos/Edit.cshtml
@model Gestion_de_Recursos_Humanos.Models.cargos

@{
    ViewBag.Title = "Editar";
}

<h2 style="text-align:center">Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal" style="margin-left:25%">
      
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.cargo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cargo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cargo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GRH/Gestion de Recursos Humanos/Gestion de Recursos Humanos/Views/cargos/Index.cshtml
@model IEnumerable<Gestion_de_Recursos_Humanos.Models.cargos>

@{
    ViewBag.Title = "Index";
}

<h2 style="text-align:center;margin-top:5%">Gestor de Cargos</h2>


<table class="table" style="margin-left:5%">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.cargo)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.cargo)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Detalles", "Details", new { id = item.Id }) |
                @Html.ActionLink("Eliminar", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>
<input type="submit" onclick="location.href='@Url.Action("Create", "cargos")'" value="Registrar Nuevo Cargo" class="btn btn-primary" style="float:right" />